### ISSUE TITLE
在 local.py文件的哪里修改server host and/or port ？

### ISSUE THREAD

**Issue by luckypoem** [tuoxie007/simple-encrypted-socks5-proxy#1]
你说"Config your server host and/or port in the local.py"，但是在 local.py文件的哪里修改server host and/or port ？我没看见修改的地方。按照你的readme,我未翻墙成功。还需要修改 local.py文件才行吗

**Comment by tuoxie007** [comment]
不好意思，没写清楚，我的意思是，配置 local.py 的 server host and/or port，应该在 config.py 里改
