### ISSUE TITLE
server.py 服务不成功

### ISSUE THREAD

**Issue by q962** [tuoxie007/simple-encrypted-socks5-proxy#3]
书写错误
https://github.com/tuoxie007/simple-encrypted-socks5-proxy/blob/e0ea6b34f50b6eba3cce86ac9fe4a59b53f829e2/server.py#L86

---

服务器启动 .server.py

```
[52:59] 正在开始: 测试 1: 连接到代理服务器
[52:59] IP 地址: 
[52:59] 已建立连接
[52:59] 测试已通过。
[52:59] 正在开始: 测试 2: 通过代理服务器连接
[56:09] 测试已停止
```

客户端工具一直等待，服务器也没有输出
终止程序，客户端有反馈

**Comment by tuoxie007** [comment]
抱起，没看懂你的问题，这个项目多年没有维护了，但是我又重新测试了一遍，可用。

测试方法：

1. 配置：

```python
server_bind_addr = ("0.0.0.0", 3030)
local_bind_addr = ("127.0.0.1", 7070)

server_proxy_addr = ("127.0.0.1", server_bind_addr[1])
```
2. 启动

```bash
$ ./server.py

$ ./local.py
```

3. 设置你的客户端

代理协议：SOCKS5
代理IP：127.0.0.1
代理端口：7070

4. 访问你的网站

**Comment by q962** [comment]
好吧，主要是没搞懂

> 在本地计算机上运行local.py
在远程服务器上运行server.py

和
> server_proxy_addr = ("your_remote_proxy_ip", server_bind_addr[1])


现在明白了

**Comment by q962** [comment]
在我的理解中就是 开启一个代理，客户端直连，

你这个中间又多了层转发，理解的不知道对不对
